

# site icon
favicon: /yx.png

# author headimg
headimg: /favicon.png
# author info
name: 语者
description: Every thing will be fine

# search
search: 
    enable: true
    placeholder: Enter Key...

# sidebar
sidebar: 
  enable: true
  menus:
    -
      name: Weibo
      link: http://weibo.com/
      target: _blank

# count(统计)
count:
  enable: true

# comments
comments:
  duoshuo_username:  justpsvm
  #disqus_username: justpsvm

# accounts support weibo/github/zhihu/twitter/douban 
# display to former three
#社区地址
social: 
  -
    name: yuque
    link: https://www.yuque.com/yuque_iq
  -
    name: github
    link: https://github.com/lanxiaozhu?tab=repositories
  # -
  #   name: zhihu
  #   link: https://www.zhihu.com/
#  -
#    name: twitter
#    link: 
#  -
#    name: douban
#    link: 





